// OSRS Location Guesser — Location Data
// x, y: normalized (0–1) coordinates on osrs_map.png, measured from top-left
// image: path relative to osrs_location_guesser/ directory, or null (→ canvas crop fallback)
// cropZoom: fraction of map width to crop (smaller = more zoomed in for canvas crops)

const LOCATIONS = [
  {
    id: 'grand_exchange',
    name: 'Grand Exchange',
    image: 'img/GE_picture.png',
    hint: 'The busiest trading hub in all of Gielinor, just north-west of Varrock.',
    x: 0.7176,
    y: 0.3391,
    cropZoom: 0.12,
  },
  {
    id: 'east_varrock',
    name: 'East Varrock',
    image: 'img/east_varrock.png',
    hint: 'The eastern district of Varrock, known for its bustling market and historic architecture.',
    x: 0.7514,
    y: 0.3730,
    cropZoom: 0.12,
  },
  {
    id: 'lumber_yard',
    name: 'Lumber Yard',
    image: 'img/lumber_yard.png',
    hint: 'A bustling area filled with trees and lumberjacks, located near the edge of Varrock.',
    x: 0.7678,
    y: 0.3261,
    cropZoom: 0.12,
  },
  {
    id: 'goblin_village',
    name: 'Goblin Village',
    image: 'img/goblin_village.png',
    hint: 'A small settlement inhabited by goblins, located just west of the Grand Exchange.',
    x: 0.6503,
    y: 0.3269,
    cropZoom: 0.12,
  },
  {
    id: 'draynor_village',
    name: 'Draynor Village',
    image: 'img/draynor_village.png',
    hint: 'A quiet village located south of Edgeville.',
    x: 0.6920,
    y: 0.4549,
    cropZoom: 0.12,
  },
  {
    id: 'draynor_manor',
    name: 'Draynor Manor',
    image: 'img/draynor_manor.png',
    hint: 'A grand estate located on the outskirts of Draynor Village.',
    x: 0.6994,
    y: 0.4008,
    cropZoom: 0.12,
  },
  {
    id: 'lumbridge_castle',
    name: 'Lumbridge Castle',
    image: 'img/lumbridge.png',
    hint: 'A majestic castle located in the heart of Lumbridge.',
    x: 0.7338,
    y: 0.4626,
    cropZoom: 0.12,
  },
  {
    id: 'wizard_tower',
    name: 'Wizard Tower',
    image: 'img/wizard_tower.png',
    hint: 'A tall tower where wizards practice their magic.',
    x: 0.7004,
    y: 0.4888,
    cropZoom: 0.12,
  },
  {
    id: 'shantay_pass',
    name: 'Shantay Pass',
    image: 'img/shantay_pass.png',
    hint: 'A narrow pass through the desert, guarded by the Shantay guards.',
    x: 0.7629,
    y: 0.5081,
    cropZoom: 0.12,
  },
  {
    id: 'mage_training',
    name: 'Mage Training Arena',
    image: 'img/mage_training.png',
    hint: 'A training ground for aspiring mages, located in the heart of the city.',
    x: 0.7824,
    y: 0.4260,
    cropZoom: 0.12,
  },
  {
    id: 'wildy_mines',
    name: 'Wildy Mines',
    image: 'img/wildy_mines.png',
    hint: 'A dangerous area filled with dangerous creatures and valuable minerals.',
    x: 0.6701,
    y: 0.2910,
    cropZoom: 0.12,
  },
  {
    id: 'barbarian_village',
    name: 'Barbarian Village',
    image: 'img/barbarian_village.png',
    hint: 'A primitive settlement inhabited by barbarians, located in the wilderness.',
    x: 0.6905,
    y: 0.3690,
    cropZoom: 0.12,
  },
  {
    id: 'body_altar',
    name: 'Body Altar',
    image: 'img/body_altar.png',
    hint: 'A sacred site dedicated to the worship of the Body god.',
    x: 0.6817,
    y: 0.3600,
    cropZoom: 0.12,
  },
  {
    id: 'dwarven_mine',
    name: 'Dwarven Mine',
    image: 'img/dwarven_mine.png',
    hint: 'A vast underground mine where dwarves extract precious ores.',
    x: 0.6694,
    y: 0.3559,
    cropZoom: 0.12,
  },
  {
    id: 'falador',
    name: 'Falador',
    image: 'img/falador.png',
    hint: 'A bustling town located in the center of Gielinor.',
    x: 0.6526,
    y: 0.4096,
    cropZoom: 0.12,
  },
  {
    id: 'port_sarim',
    name: 'Port Sarim',
    image: 'img/port_sarim.png',
    hint: 'A busy port town located on the coast of Gielinor.',
    x: 0.6806,
    y: 0.4549,
    cropZoom: 0.12,
  },
  {
    id: 'mudskipper',
    name: 'Mudskipper',
    image: 'img/mudskipper.png',
    hint: 'A small fishing village located on the coast of Gielinor.',
    x: 0.6628,
    y: 0.4961,
    cropZoom: 0.12,
  },
  {
    id: 'rimmington',
    name: 'Rimmington',
    image: 'img/rimmington.png',
    hint: 'A peaceful town located in the countryside of Gielinor.',
    x: 0.6493,
    y: 0.4650,
    cropZoom: 0.12,
  },
  {
    id: 'crafting_guild',
    name: 'Crafting Guild',
    image: 'img/crafting_guild.png',
    hint: 'A guild where skilled craftsmen train and work.',
    x: 0.6426,
    y: 0.4292,
    cropZoom: 0.12,
  },
  {
    id: 'lumbridge_swamp',
    name: 'Lumbridge Swamp',
    image: 'img/lumbridge_swamp.png',
    hint: 'A murky swamp located near Lumbridge.',
    x: 0.7283,
    y: 0.4833,
    cropZoom: 0.12,
  },
  {
    id: 'lumbridge_fishing',
    name: 'Lumbridge Fishing Spot',
    image: 'img/lumbridge_fishing.png',
    hint: 'A popular fishing spot located near Lumbridge.',
    x: 0.7439,
    y: 0.4888,
    cropZoom: 0.12,
  },
  {
    id: 'lumbridge_center',
    name: 'Lumbridge Center',
    image: 'img/lumbridge_center.png',
    hint: 'The heart of Lumbridge, where most activities take place.',
    x: 0.7405,
    y: 0.4690,
    cropZoom: 0.12,
  },
  {
    id: 'lumbridge_cows',
    name: 'Lumbridge Cows',
    image: 'img/lumbridge_cows.png',
    hint: 'A peaceful area where cows graze in the countryside of Lumbridge.',
    x: 0.7471,
    y: 0.4360,
    cropZoom: 0.12,
  },
  {
    id: 'lumbridge_north',
    name: 'Lumbridge North',
    image: 'img/lumbridge_north.png',
    hint: 'The northern part of Lumbridge, known for its peaceful atmosphere.',
    x: 0.7185,
    y: 0.4291,
    cropZoom: 0.12,
  },
  {
    id: 'scorpion_pit',
    name: 'Scorpion Pit',
    image: 'img/scorpion_pit.png',
    hint: 'A dangerous area filled with scorpions and other deadly creatures.',
    x: 0.7405,
    y: 0.1264,
    cropZoom: 0.12,
  },
  {
    id: 'lava_dragon',
    name: 'Lava Dragon',
    image: 'img/lava_dragon.png',
    hint: 'A fierce dragon that lives in the lava of the volcanic region.',
    x: 0.7262,
    y: 0.1726,
    cropZoom: 0.12,
  },
  {
    id: 'obelisk_wildy',
    name: 'Obelisk of the Wildy',
    image: 'img/obelisk_wildy.png',
    hint: 'A mysterious obelisk located in the wilderness.',
    x: 0.7382,
    y: 0.2551,
    cropZoom: 0.12,
  },
  {
    id: 'clan_wars',
    name: 'Clan Wars',
    image: 'img/clan_wars.png',
    hint: 'A contested area where clans battle for control.',
    x: 0.7082,
    y: 0.2731,
    cropZoom: 0.12,
  },
  {
    id: 'wildy_edge',
    name: 'Wildy Edge',
    image: 'img/wildy_edge.png',
    hint: 'The edge of the wilderness, a dangerous area filled with hostile creatures.',
    x: 0.7087,
    y: 0.3223,
    cropZoom: 0.12,
  },
  {
    id: 'falador_park',
    name: 'Falador Park',
    image: 'img/falador_park.png',
    hint: 'A beautiful park located in the heart of Falador.',
    x: 0.6647,
    y: 0.3864,
    cropZoom: 0.12,
  },
];
