// OSRS Location Guesser — Location Data
// x, y: normalized (0–1) coordinates on osrs_map.png, measured from top-left
// image: path relative to osrs_location_guesser/ directory, or null (→ canvas crop fallback)
// cropZoom: fraction of map width to crop (smaller = more zoomed in for canvas crops)

const LOCATIONS = [
  {
    id: 'grand_exchange',
    name: 'Grand Exchange',
    image: 'img/GE_picture.png',
    hint: 'The busiest trading hub in all of Gielinor, just north-west of Varrock.',
    x: 0.7176,
    y: 0.3391,
    cropZoom: 0.12,
  },
  {
    id: 'east_varrock',
    name: 'East Varrock',
    image: 'img/east_varrock.png',
    hint: 'The eastern district of Varrock, known for its bustling market and historic architecture.',
    x: 0.7514,
    y: 0.3730,
    cropZoom: 0.12,
  },
  {
    id: 'lumber_yard',
    name: 'Lumber Yard',
    image: 'img/lumber_yard.png',
    hint: 'A bustling area filled with trees and lumberjacks, located near the edge of Varrock.',
    x: 0.7678,
    y: 0.3261,
    cropZoom: 0.12,
  },
  {
    id: 'goblin_village',
    name: 'Goblin Village',
    image: 'img/goblin_village.png',
    hint: 'A small settlement inhabited by goblins, located just west of the Grand Exchange.',
    x: 0.6503,
    y: 0.3269,
    cropZoom: 0.12,
  },
  {
    id: 'draynor_village',
    name: 'Draynor Village',
    image: 'img/draynor_village.png',
    hint: 'A quiet village located south of Edgeville.',
    x: 0.6920,
    y: 0.4549,
    cropZoom: 0.12,
  },
  {
    id: 'draynor_manor',
    name: 'Draynor Manor',
    image: 'img/draynor_manor.png',
    hint: 'A grand estate located on the outskirts of Draynor Village.',
    x: 0.6994,
    y: 0.4008,
    cropZoom: 0.12,
  },
  {
    id: 'lumbridge_castle',
    name: 'Lumbridge Castle',
    image: 'img/lumbridge.png',
    hint: 'A majestic castle located in the heart of Lumbridge.',
    x: 0.7338,
    y: 0.4626,
    cropZoom: 0.12,
  },
  {
    id: 'wizard_tower',
    name: 'Wizard Tower',
    image: 'img/wizard_tower.png',
    hint: 'A tall tower where wizards practice their magic.',
    x: 0.7004,
    y: 0.4888,
    cropZoom: 0.12,
  },
  {
    id: 'shantay_pass',
    name: 'Shantay Pass',
    image: 'img/shantay_pass.png',
    hint: 'A narrow pass through the desert, guarded by the Shantay guards.',
    x: 0.7629,
    y: 0.5081,
    cropZoom: 0.12,
  },
  {
    id: 'mage_training',
    name: 'Mage Training Arena',
    image: 'img/mage_training.png',
    hint: 'A training ground for aspiring mages, located in the heart of the city.',
    x: 0.7824,
    y: 0.4260,
    cropZoom: 0.12,
  },
  {
    id: 'wildy_mines',
    name: 'Wildy Mines',
    image: 'img/wildy_mines.png',
    hint: 'A dangerous area filled with dangerous creatures and valuable minerals.',
    x: 0.6701,
    y: 0.2910,
    cropZoom: 0.12,
  },
];
