var PLAYLIST = [
  { "name": "Mr. Brightside", "artistNames": "The Killers" },
  { "name": "Iris", "artistNames": "The Goo Goo Dolls" },
  { "name": "Wonderwall", "artistNames": "Oasis" },
  { "name": "Californication", "artistNames": "Red Hot Chili Peppers" },
  { "name": "All The Small Things", "artistNames": "blink-182" },
  { "name": "Somebody Told Me", "artistNames": "The Killers" },
  { "name": "Centuries", "artistNames": "Fall Out Boy" },
  { "name": "Basket Case", "artistNames": "Green Day" },
  { "name": "21 Guns", "artistNames": "Green Day" },
  { "name": "It's Tricky", "artistNames": "Run-D.M.C." },
  { "name": "In The Air Tonight", "artistNames": "Phil Collins" },
  { "name": "Sweet Child O' Mine", "artistNames": "Guns N' Roses" },
  { "name": "Sandstorm", "artistNames": "Darude" },
  { "name": "Take Me Home", "artistNames": "Cash Cash, Bebe Rexha" },
  { "name": "Clarity", "artistNames": "Zedd, Foxes" },
  { "name": "Runaway (U & I)", "artistNames": "Galantis" },
  { "name": "Pompeii", "artistNames": "Bastille" },
  { "name": "Titanium", "artistNames": "David Guetta, Sia" },
  { "name": "Don't You Worry Child", "artistNames": "Swedish House Mafia, John Martin" },
  { "name": "Hey Ya!", "artistNames": "Outkast" },
  { "name": "Ignition (Remix)", "artistNames": "R. Kelly" },
  { "name": "Crazy In Love", "artistNames": "Beyoncé, JAY-Z" },
  { "name": "Empire State Of Mind", "artistNames": "JAY-Z, Alicia Keys" },
  { "name": "Drops of Jupiter", "artistNames": "Train" },
  { "name": "Crazy", "artistNames": "Gnarls Barkley" },
  { "name": "Complicated", "artistNames": "Avril Lavigne" },
  { "name": "Where Is The Love?", "artistNames": "Black Eyed Peas" },
  { "name": "Sugar, We're Goin Down", "artistNames": "Fall Out Boy" },
  { "name": "Livin' la Vida Loca", "artistNames": "Ricky Martin" },
  { "name": "I'm Yours", "artistNames": "Jason Mraz" },
  { "name": "Breakeven", "artistNames": "The Script" },
  { "name": "For the First Time", "artistNames": "The Script" },
  { "name": "Party In The U.S.A.", "artistNames": "Miley Cyrus" },
  { "name": "Stacy's Mom", "artistNames": "Fountains Of Wayne" },
  { "name": "Wake Me up Before You Go-Go", "artistNames": "Wham!" },
  { "name": "This Love", "artistNames": "Maroon 5" },
  { "name": "Man! I Feel Like A Woman!", "artistNames": "Shania Twain" },
  { "name": "American Idiot", "artistNames": "Green Day" },
  { "name": "Video Killed The Radio Star", "artistNames": "The Buggles" },
  { "name": "Sk8er Boi", "artistNames": "Avril Lavigne" },
  { "name": "Toxic", "artistNames": "Britney Spears" },
  { "name": "It Wasn't Me", "artistNames": "Shaggy, Rik Rok" },
  { "name": "She Will Be Loved", "artistNames": "Maroon 5" },
  { "name": "Burnin' Up", "artistNames": "Jonas Brothers" },
  { "name": "S.O.S.", "artistNames": "Jonas Brothers" },
  { "name": "Beautiful Soul", "artistNames": "Jesse McCartney" },
  { "name": "Love Yourself", "artistNames": "Justin Bieber" },
  { "name": "Shake It", "artistNames": "Metro Station" },
  { "name": "We R Who We R", "artistNames": "Kesha" },
  { "name": "Pumped Up Kicks", "artistNames": "Foster The People" },
  { "name": "Rude", "artistNames": "MAGIC!" },
  { "name": "Get Lucky", "artistNames": "Daft Punk, Pharrell Williams" },
  { "name": "Summer", "artistNames": "Calvin Harris" },
  { "name": "Hey, Soul Sister", "artistNames": "Train" },
  { "name": "Roses", "artistNames": "The Chainsmokers, ROZES" },
  { "name": "Shut Up and Dance", "artistNames": "WALK THE MOON" },
  { "name": "Hall of Fame", "artistNames": "The Script, will.i.am" },
  { "name": "Chandelier", "artistNames": "Sia" },
  { "name": "Faded", "artistNames": "Alan Walker" },
  { "name": "Mirrors", "artistNames": "Justin Timberlake" },
  { "name": "Take Me To Church", "artistNames": "Hozier" },
  { "name": "Firework", "artistNames": "Katy Perry" },
  { "name": "Somebody That I Used To Know", "artistNames": "Gotye, Kimbra" },
  { "name": "Feel So Close", "artistNames": "Calvin Harris" },
  { "name": "Best Song Ever", "artistNames": "One Direction" },
  { "name": "TiK ToK", "artistNames": "Kesha" },
  { "name": "Give Me Everything", "artistNames": "Pitbull, Ne-Yo" },
  { "name": "Rolling in the Deep", "artistNames": "Adele" },
  { "name": "Hotline Bling", "artistNames": "Drake" },
  { "name": "Just the Way You Are", "artistNames": "Bruno Mars" },
  { "name": "Timber", "artistNames": "Pitbull, Kesha" },
  { "name": "Royals", "artistNames": "Lorde" },
  { "name": "Loyal", "artistNames": "Chris Brown, Lil Wayne, Tyga" },
  { "name": "Replay", "artistNames": "Iyaz" },
  { "name": "Billionaire", "artistNames": "Travie McCoy, Bruno Mars" },
  { "name": "In My Head", "artistNames": "Jason Derulo" },
  { "name": "Paparazzi", "artistNames": "Lady Gaga" },
  { "name": "Teenage Dream", "artistNames": "Katy Perry" },
  { "name": "Whataya Want from Me", "artistNames": "Adam Lambert" },
  { "name": "Sweet Dreams", "artistNames": "Beyoncé" },
  { "name": "Club Can't Handle Me", "artistNames": "Flo Rida" },
  { "name": "Cooler Than Me", "artistNames": "Mike Posner" },
  { "name": "Haven't Met You Yet", "artistNames": "Michael Bublé" },
  { "name": "I Gotta Feeling", "artistNames": "Black Eyed Peas" },
  { "name": "Fireflies", "artistNames": "Owl City" },
  { "name": "Sorry", "artistNames": "Justin Bieber" },
  { "name": "Young, Wild & Free", "artistNames": "Snoop Dogg, Wiz Khalifa, Bruno Mars" },
  { "name": "Whistle", "artistNames": "Flo Rida" },
  { "name": "Airplanes", "artistNames": "B.o.B, Hayley Williams" },
  { "name": "Trumpets", "artistNames": "Jason Derulo" },
  { "name": "Oops!...I Did It Again", "artistNames": "Britney Spears" },
  { "name": "This Is What You Came For", "artistNames": "Calvin Harris, Rihanna" },
  { "name": "Beauty And A Beat", "artistNames": "Justin Bieber, Nicki Minaj" },
  { "name": "Waiting For Love", "artistNames": "Avicii" },

  { "name": "Smells Like Teen Spirit", "artistNames": "Nirvana" },
  { "name": "Come As You Are", "artistNames": "Nirvana" },
  { "name": "Wannabe", "artistNames": "Spice Girls" },
  { "name": "I Want It That Way", "artistNames": "Backstreet Boys" },
  { "name": "Everybody", "artistNames": "Backstreet Boys" },
  { "name": "Bye Bye Bye", "artistNames": "NSYNC" },
  { "name": "Tearin' Up My Heart", "artistNames": "NSYNC" },
  { "name": "No Scrubs", "artistNames": "TLC" },
  { "name": "Waterfalls", "artistNames": "TLC" },
  { "name": "Say My Name", "artistNames": "Destiny's Child" },
  { "name": "Survivor", "artistNames": "Destiny's Child" },
  { "name": "Bootylicious", "artistNames": "Destiny's Child" },
  { "name": "Vogue", "artistNames": "Madonna" },
  { "name": "Like A Prayer", "artistNames": "Madonna" },
  { "name": "I Will Always Love You", "artistNames": "Whitney Houston" },
  { "name": "Fantasy", "artistNames": "Mariah Carey" },
  { "name": "Always Be My Baby", "artistNames": "Mariah Carey" },
  { "name": "Emotions", "artistNames": "Mariah Carey" },
  { "name": "The Sign", "artistNames": "Ace of Base" },
  { "name": "All That She Wants", "artistNames": "Ace of Base" },
  { "name": "Ironic", "artistNames": "Alanis Morissette" },
  { "name": "You Oughta Know", "artistNames": "Alanis Morissette" },
  { "name": "Don't Speak", "artistNames": "No Doubt" },
  { "name": "Just a Girl", "artistNames": "No Doubt" },
  { "name": "All I Wanna Do", "artistNames": "Sheryl Crow" },
  { "name": "I Believe I Can Fly", "artistNames": "R. Kelly" },
  { "name": "End of the Road", "artistNames": "Boyz II Men" },
  { "name": "I'll Make Love to You", "artistNames": "Boyz II Men" },
  { "name": "What Is Love", "artistNames": "Haddaway" },
  { "name": "Gangsta's Paradise", "artistNames": "Coolio" },
  { "name": "California Love", "artistNames": "2Pac, Dr. Dre" },
  { "name": "Hypnotize", "artistNames": "The Notorious B.I.G." },
  { "name": "Gettin' Jiggy Wit It", "artistNames": "Will Smith" },
  { "name": "Men In Black", "artistNames": "Will Smith" },
  { "name": "Truly Madly Deeply", "artistNames": "Savage Garden" },
  { "name": "I Want You", "artistNames": "Savage Garden" },
  { "name": "Zombie", "artistNames": "The Cranberries" },
  { "name": "Closing Time", "artistNames": "Semisonic" },
  { "name": "Semi-Charmed Life", "artistNames": "Third Eye Blind" },
  { "name": "3 AM", "artistNames": "Matchbox Twenty" },
  { "name": "Unwell", "artistNames": "Matchbox Twenty" },
  { "name": "Angel", "artistNames": "Sarah McLachlan" },
  { "name": "My Heart Will Go On", "artistNames": "Celine Dion" },
  { "name": "Mambo No. 5", "artistNames": "Lou Bega" },
  { "name": "All Star", "artistNames": "Smash Mouth" },
  { "name": "One Week", "artistNames": "Barenaked Ladies" },
  { "name": "MMMBop", "artistNames": "Hanson" },
  { "name": "Loser", "artistNames": "Beck" },
  { "name": "Save Tonight", "artistNames": "Eagle-Eye Cherry" },
  { "name": "Good Riddance (Time of Your Life)", "artistNames": "Green Day" },
  { "name": "What's My Age Again?", "artistNames": "blink-182" },
  { "name": "Dammit", "artistNames": "blink-182" },
  { "name": "The Way", "artistNames": "Fastball" },
  { "name": "Smooth", "artistNames": "Santana, Rob Thomas" },
  { "name": "Limp Bizkit - Nookie", "artistNames": "Limp Bizkit" },
  { "name": "Freak on a Leash", "artistNames": "Korn" },
  { "name": "With Arms Wide Open", "artistNames": "Creed" },
  { "name": "Higher", "artistNames": "Creed" },
  { "name": "Hemorrhage (In My Hands)", "artistNames": "Fuel" },
  { "name": "Behind Blue Eyes", "artistNames": "Limp Bizkit" },

  { "name": "In Da Club", "artistNames": "50 Cent" },
  { "name": "Candy Shop", "artistNames": "50 Cent" },
  { "name": "Lose Yourself", "artistNames": "Eminem" },
  { "name": "Without Me", "artistNames": "Eminem" },
  { "name": "Yeah!", "artistNames": "Usher, Lil Jon, Ludacris" },
  { "name": "Confessions Part II", "artistNames": "Usher" },
  { "name": "Burn", "artistNames": "Usher" },
  { "name": "Fallin'", "artistNames": "Alicia Keys" },
  { "name": "No One", "artistNames": "Alicia Keys" },
  { "name": "Since U Been Gone", "artistNames": "Kelly Clarkson" },
  { "name": "Breakaway", "artistNames": "Kelly Clarkson" },
  { "name": "Beautiful", "artistNames": "Christina Aguilera" },
  { "name": "Gold Digger", "artistNames": "Kanye West, Jamie Foxx" },
  { "name": "Stronger", "artistNames": "Kanye West" },
  { "name": "Lollipop", "artistNames": "Lil Wayne" },
  { "name": "Low", "artistNames": "Flo Rida, T-Pain" },
  { "name": "Smack That", "artistNames": "Akon, Eminem" },
  { "name": "Lonely", "artistNames": "Akon" },
  { "name": "Beautiful Girls", "artistNames": "Sean Kingston" },
  { "name": "Hey There Delilah", "artistNames": "Plain White T's" },
  { "name": "Cupid's Chokehold", "artistNames": "Gym Class Heroes" },
  { "name": "Welcome to the Black Parade", "artistNames": "My Chemical Romance" },
  { "name": "Teenagers", "artistNames": "My Chemical Romance" },
  { "name": "Misery Business", "artistNames": "Paramore" },
  { "name": "The Only Exception", "artistNames": "Paramore" },
  { "name": "Chasing Cars", "artistNames": "Snow Patrol" },
  { "name": "Run", "artistNames": "Snow Patrol" },
  { "name": "The Scientist", "artistNames": "Coldplay" },
  { "name": "Yellow", "artistNames": "Coldplay" },
  { "name": "Clocks", "artistNames": "Coldplay" },
  { "name": "Fix You", "artistNames": "Coldplay" },
  { "name": "How You Remind Me", "artistNames": "Nickelback" },
  { "name": "Photograph", "artistNames": "Nickelback" },
  { "name": "In the End", "artistNames": "Linkin Park" },
  { "name": "Numb", "artistNames": "Linkin Park" },
  { "name": "Crawling", "artistNames": "Linkin Park" },
  { "name": "Bring Me to Life", "artistNames": "Evanescence" },
  { "name": "My Immortal", "artistNames": "Evanescence" },
  { "name": "Seven Nation Army", "artistNames": "The White Stripes" },
  { "name": "Feel Good Inc.", "artistNames": "Gorillaz" },
  { "name": "Rehab", "artistNames": "Amy Winehouse" },
  { "name": "Valerie", "artistNames": "Amy Winehouse" },
  { "name": "Paper Planes", "artistNames": "M.I.A." },
  { "name": "Kids", "artistNames": "MGMT" },
  { "name": "Poker Face", "artistNames": "Lady Gaga" },
  { "name": "Bad Romance", "artistNames": "Lady Gaga" },
  { "name": "Telephone", "artistNames": "Lady Gaga, Beyoncé" },
  { "name": "I Kissed a Girl", "artistNames": "Katy Perry" },
  { "name": "Roar", "artistNames": "Katy Perry" },
  { "name": "Umbrella", "artistNames": "Rihanna" },
  { "name": "Disturbia", "artistNames": "Rihanna" },
  { "name": "We Found Love", "artistNames": "Rihanna, Calvin Harris" },
  { "name": "SexyBack", "artistNames": "Justin Timberlake" },
  { "name": "What Goes Around...Comes Around", "artistNames": "Justin Timberlake" },
  { "name": "Love Story", "artistNames": "Taylor Swift" },
  { "name": "You Belong With Me", "artistNames": "Taylor Swift" },
  { "name": "So Sick", "artistNames": "Ne-Yo" },
  { "name": "Buy U a Drank", "artistNames": "T-Pain, Yung Joc" },
  { "name": "Run It!", "artistNames": "Chris Brown" },
  { "name": "With You", "artistNames": "Chris Brown" },
  { "name": "Single Ladies", "artistNames": "Beyoncé" },
  { "name": "Halo", "artistNames": "Beyoncé" },
  { "name": "Boom Boom Pow", "artistNames": "Black Eyed Peas" },
  { "name": "Party Rock Anthem", "artistNames": "LMFAO, Lauren Bennett, GoonRock" },
  { "name": "We Are Young", "artistNames": "fun., Janelle Monáe" },
  { "name": "Call Me Maybe", "artistNames": "Carly Rae Jepsen" },
  { "name": "Gangnam Style", "artistNames": "PSY" },
  { "name": "What Makes You Beautiful", "artistNames": "One Direction" },
  { "name": "Thrift Shop", "artistNames": "Macklemore, Ryan Lewis, Wanz" },
  { "name": "Happy", "artistNames": "Pharrell Williams" },
  { "name": "All of Me", "artistNames": "John Legend" },
  { "name": "Stay With Me", "artistNames": "Sam Smith" },
  { "name": "Thinking Out Loud", "artistNames": "Ed Sheeran" },
  { "name": "Blank Space", "artistNames": "Taylor Swift" },
  { "name": "Shake It Off", "artistNames": "Taylor Swift" },
  { "name": "Can't Feel My Face", "artistNames": "The Weeknd" },
  { "name": "Blinding Lights", "artistNames": "The Weeknd" },
  { "name": "One Dance", "artistNames": "Drake" },
  { "name": "God's Plan", "artistNames": "Drake" },
  { "name": "Rockstar", "artistNames": "Post Malone, 21 Savage" },
  { "name": "Sunflower", "artistNames": "Post Malone, Swae Lee" },
  { "name": "bad guy", "artistNames": "Billie Eilish" },
  { "name": "Thank U, Next", "artistNames": "Ariana Grande" },
  { "name": "Problem", "artistNames": "Ariana Grande, Iggy Azalea" },
  { "name": "Shape of You", "artistNames": "Ed Sheeran" },
  { "name": "Perfect", "artistNames": "Ed Sheeran" },
  { "name": "HUMBLE.", "artistNames": "Kendrick Lamar" },
  { "name": "Redbone", "artistNames": "Childish Gambino" },
  { "name": "Bodak Yellow", "artistNames": "Cardi B" },
  { "name": "Old Town Road", "artistNames": "Lil Nas X, Billy Ray Cyrus" },
  { "name": "Levitating", "artistNames": "Dua Lipa" },
  { "name": "New Rules", "artistNames": "Dua Lipa" },
  { "name": "Watermelon Sugar", "artistNames": "Harry Styles" },
  { "name": "Closer", "artistNames": "The Chainsmokers, Halsey" },
  { "name": "Stressed Out", "artistNames": "Twenty One Pilots" },
  { "name": "Ride", "artistNames": "Twenty One Pilots" },
  { "name": "Radioactive", "artistNames": "Imagine Dragons" },
  { "name": "Thunder", "artistNames": "Imagine Dragons" },
  { "name": "Believer", "artistNames": "Imagine Dragons" },
  { "name": "High Hopes", "artistNames": "Panic! at the Disco" },
  { "name": "Without Me", "artistNames": "Halsey" },
  { "name": "Bad at Love", "artistNames": "Halsey" },
  { "name": "Havana", "artistNames": "Camila Cabello, Young Thug" },
  { "name": "Despacito", "artistNames": "Luis Fonsi, Daddy Yankee" },
  { "name": "Rather Be", "artistNames": "Clean Bandit, Jess Glynne" },
  { "name": "Rockabye", "artistNames": "Clean Bandit, Sean Paul, Anne-Marie" },
  { "name": "Stitches", "artistNames": "Shawn Mendes" },
  { "name": "There's Nothing Holdin' Me Back", "artistNames": "Shawn Mendes" },
  { "name": "Grenade", "artistNames": "Bruno Mars" },
  { "name": "Locked Out of Heaven", "artistNames": "Bruno Mars" },
  { "name": "Uptown Funk", "artistNames": "Mark Ronson, Bruno Mars" },
  { "name": "Someone Like You", "artistNames": "Adele" },
  { "name": "Hello", "artistNames": "Adele" },
  { "name": "Radioactive", "artistNames": "Imagine Dragons" },
  { "name": "Counting Stars", "artistNames": "OneRepublic" },
  { "name": "Apologize", "artistNames": "Timbaland, OneRepublic" },
  { "name": "Rather Be", "artistNames": "Clean Bandit, Jess Glynne" },
  { "name": "Suit & Tie", "artistNames": "Justin Timberlake, JAY-Z" },
  { "name": "Can't Stop the Feeling!", "artistNames": "Justin Timberlake" },
  { "name": "Shallow", "artistNames": "Lady Gaga, Bradley Cooper" },
  { "name": "A Sky Full of Stars", "artistNames": "Coldplay" },
  { "name": "Something Just Like This", "artistNames": "The Chainsmokers, Coldplay" },
  { "name": "Lean On", "artistNames": "Major Lazer, MO, DJ Snake" },
  { "name": "Sorry", "artistNames": "Justin Bieber" },
  { "name": "What Do You Mean?", "artistNames": "Justin Bieber" },
  { "name": "Stay", "artistNames": "Rihanna, Mikky Ekko" },
  { "name": "Diamonds", "artistNames": "Rihanna" },
  { "name": "Don't Stop Me Now", "artistNames": "Queen" },
  { "name": "Bohemian Rhapsody", "artistNames": "Queen" },
  { "name": "We Will Rock You", "artistNames": "Queen" },
  { "name": "Under Pressure", "artistNames": "Queen, David Bowie" },
  { "name": "Eye of the Tiger", "artistNames": "Survivor" },
  { "name": "Don't Stop Believin'", "artistNames": "Journey" },
  { "name": "Africa", "artistNames": "Toto" },
  { "name": "Take On Me", "artistNames": "a-ha" },
  { "name": "Girls Just Want to Have Fun", "artistNames": "Cyndi Lauper" },
  { "name": "Come on Eileen", "artistNames": "Dexys Midnight Runners" },
  { "name": "Walking on Sunshine", "artistNames": "Katrina and the Waves" },
  { "name": "99 Luftballons", "artistNames": "Nena" },
  { "name": "Sweet Dreams (Are Made of This)", "artistNames": "Eurythmics" },
  { "name": "Tainted Love", "artistNames": "Soft Cell" }
];
